/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryRouteImport } from './routes/$country'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassRouteImport } from './routes/pass'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as CountryIndexRouteImport } from './routes/$country.index'
import { Route as CountryCityRouteImport } from './routes/$country.$city'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskSlugRouteImport } from './routes/desk.$slug'
import { Route as LetterUnsubscribeRouteImport } from './routes/letter.unsubscribe'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as PayReturnRouteImport } from './routes/pay.return'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentWebhookAlipayRouteImport } from './routes/api/payment/webhook/alipay'
import { Route as ApiPaymentWebhookEasypayRouteImport } from './routes/api/payment/webhook/easypay'
import { Route as ApiPaymentWebhookStripeRouteImport } from './routes/api/payment/webhook/stripe'
import { Route as ApiPaymentWebhookWxpayRouteImport } from './routes/api/payment/webhook/wxpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryRoute = CountryRouteImport.update({
  id: '/$country',
  path: '/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryRoute,
} as any)
const CountryCityRoute = CountryCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => CountryRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSlugRoute = DeskSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DeskRoute,
} as any)
const LetterUnsubscribeRoute = LetterUnsubscribeRouteImport.update({
  id: '/letter/unsubscribe',
  path: '/letter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayReturnRoute = PayReturnRouteImport.update({
  id: '/pay/return',
  path: '/pay/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookAlipayRoute = ApiPaymentWebhookAlipayRouteImport.update({
  id: '/api/payment/webhook/alipay',
  path: '/api/payment/webhook/alipay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookEasypayRoute =
  ApiPaymentWebhookEasypayRouteImport.update({
    id: '/api/payment/webhook/easypay',
    path: '/api/payment/webhook/easypay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentWebhookStripeRoute = ApiPaymentWebhookStripeRouteImport.update({
  id: '/api/payment/webhook/stripe',
  path: '/api/payment/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookWxpayRoute = ApiPaymentWebhookWxpayRouteImport.update({
  id: '/api/payment/webhook/wxpay',
  path: '/api/payment/webhook/wxpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pass': typeof PassRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$country/$city': typeof CountryCityRoute
  '/desk/$slug': typeof DeskSlugRoute
  '/letter/unsubscribe': typeof LetterUnsubscribeRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay/return': typeof PayReturnRoute
  '/$country/': typeof CountryIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/easypay': typeof ApiPaymentWebhookEasypayRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wxpay': typeof ApiPaymentWebhookWxpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pass': typeof PassRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$country/$city': typeof CountryCityRoute
  '/desk/$slug': typeof DeskSlugRoute
  '/letter/unsubscribe': typeof LetterUnsubscribeRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay/return': typeof PayReturnRoute
  '/$country': typeof CountryIndexRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/easypay': typeof ApiPaymentWebhookEasypayRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wxpay': typeof ApiPaymentWebhookWxpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$country': typeof CountryRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/desk': typeof DeskRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pass': typeof PassRoute
  '/verify-email': typeof VerifyEmailRoute
  '/$country/$city': typeof CountryCityRoute
  '/desk/$slug': typeof DeskSlugRoute
  '/letter/unsubscribe': typeof LetterUnsubscribeRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/pay/return': typeof PayReturnRoute
  '/$country/': typeof CountryIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/easypay': typeof ApiPaymentWebhookEasypayRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wxpay': typeof ApiPaymentWebhookWxpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$country'
    | '/account'
    | '/admin'
    | '/desk'
    | '/feedback'
    | '/login'
    | '/pass'
    | '/verify-email'
    | '/$country/$city'
    | '/desk/$slug'
    | '/letter/unsubscribe'
    | '/pay/$orderId'
    | '/pay/return'
    | '/$country/'
    | '/desk/'
    | '/api/auth/$'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/easypay'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wxpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/pass'
    | '/verify-email'
    | '/$country/$city'
    | '/desk/$slug'
    | '/letter/unsubscribe'
    | '/pay/$orderId'
    | '/pay/return'
    | '/$country'
    | '/desk'
    | '/api/auth/$'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/easypay'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wxpay'
  id:
    | '__root__'
    | '/'
    | '/$country'
    | '/account'
    | '/admin'
    | '/desk'
    | '/feedback'
    | '/login'
    | '/pass'
    | '/verify-email'
    | '/$country/$city'
    | '/desk/$slug'
    | '/letter/unsubscribe'
    | '/pay/$orderId'
    | '/pay/return'
    | '/$country/'
    | '/desk/'
    | '/api/auth/$'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/easypay'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wxpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryRoute: typeof CountryRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DeskRoute: typeof DeskRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  PassRoute: typeof PassRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LetterUnsubscribeRoute: typeof LetterUnsubscribeRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  PayReturnRoute: typeof PayReturnRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentWebhookAlipayRoute: typeof ApiPaymentWebhookAlipayRoute
  ApiPaymentWebhookEasypayRoute: typeof ApiPaymentWebhookEasypayRoute
  ApiPaymentWebhookStripeRoute: typeof ApiPaymentWebhookStripeRoute
  ApiPaymentWebhookWxpayRoute: typeof ApiPaymentWebhookWxpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country': {
      id: '/$country'
      path: '/$country'
      fullPath: '/$country'
      preLoaderRoute: typeof CountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/': {
      id: '/$country/'
      path: '/'
      fullPath: '/$country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof CountryRoute
    }
    '/$country/$city': {
      id: '/$country/$city'
      path: '/$city'
      fullPath: '/$country/$city'
      preLoaderRoute: typeof CountryCityRouteImport
      parentRoute: typeof CountryRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$slug': {
      id: '/desk/$slug'
      path: '/$slug'
      fullPath: '/desk/$slug'
      preLoaderRoute: typeof DeskSlugRouteImport
      parentRoute: typeof DeskRoute
    }
    '/letter/unsubscribe': {
      id: '/letter/unsubscribe'
      path: '/letter/unsubscribe'
      fullPath: '/letter/unsubscribe'
      preLoaderRoute: typeof LetterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/return': {
      id: '/pay/return'
      path: '/pay/return'
      fullPath: '/pay/return'
      preLoaderRoute: typeof PayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/alipay': {
      id: '/api/payment/webhook/alipay'
      path: '/api/payment/webhook/alipay'
      fullPath: '/api/payment/webhook/alipay'
      preLoaderRoute: typeof ApiPaymentWebhookAlipayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/easypay': {
      id: '/api/payment/webhook/easypay'
      path: '/api/payment/webhook/easypay'
      fullPath: '/api/payment/webhook/easypay'
      preLoaderRoute: typeof ApiPaymentWebhookEasypayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/stripe': {
      id: '/api/payment/webhook/stripe'
      path: '/api/payment/webhook/stripe'
      fullPath: '/api/payment/webhook/stripe'
      preLoaderRoute: typeof ApiPaymentWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/wxpay': {
      id: '/api/payment/webhook/wxpay'
      path: '/api/payment/webhook/wxpay'
      fullPath: '/api/payment/webhook/wxpay'
      preLoaderRoute: typeof ApiPaymentWebhookWxpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CountryRouteChildren {
  CountryCityRoute: typeof CountryCityRoute
  CountryIndexRoute: typeof CountryIndexRoute
}

const CountryRouteChildren: CountryRouteChildren = {
  CountryCityRoute: CountryCityRoute,
  CountryIndexRoute: CountryIndexRoute,
}

const CountryRouteWithChildren =
  CountryRoute._addFileChildren(CountryRouteChildren)

interface DeskRouteChildren {
  DeskSlugRoute: typeof DeskSlugRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskSlugRoute: DeskSlugRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryRoute: CountryRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DeskRoute: DeskRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  PassRoute: PassRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LetterUnsubscribeRoute: LetterUnsubscribeRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  PayReturnRoute: PayReturnRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentWebhookAlipayRoute: ApiPaymentWebhookAlipayRoute,
  ApiPaymentWebhookEasypayRoute: ApiPaymentWebhookEasypayRoute,
  ApiPaymentWebhookStripeRoute: ApiPaymentWebhookStripeRoute,
  ApiPaymentWebhookWxpayRoute: ApiPaymentWebhookWxpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
